version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin_postgres
      POSTGRES_PASSWORD: postgres_db
      POSTGRES_DB: edificios_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lobbysync_network

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo_db
      MONGO_INITDB_DATABASE: admin_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - lobbysync_network

  backend:
    build: .
    container_name: lobbysync_backend
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -Dfile.encoding=UTF-8
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/edificios_db
      SPRING_DATASOURCE_USERNAME: admin_postgres
      SPRING_DATASOURCE_PASSWORD: postgres_db
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_MONGODB_HOST: mongo_db
      SPRING_MONGODB_PORT: "27017"
      SPRING_MONGODB_USERNAME: admin_mongo
      SPRING_MONGODB_PASSWORD: mongo_db
      SPRING_MONGODB_AUTHENTICATION_DATABASE: admin_mongo
      FIREBASE_CONFIG_PATH: /app/serviceAccountKey.json
    depends_on:
      - postgres_db
      - mongo_db
    networks:
      - lobbysync_network
    volumes:
      - /Users/luisquijadamunoz/Downloads/serviceAccountKey.json:/app/serviceAccountKey.json:ro

volumes:
  postgres_data:
  mongo_data:

networks:
  lobbysync_network:
    driver: bridge
