version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lobbysync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lobbysync_network

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - lobbysync_network

  backend:
    build: .
    container_name: lobbysync_backend
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -Dfile.encoding=UTF-8
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/lobbysync
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_MONGODB_HOST: mongo_db
      FIREBASE_CONFIG_PATH: /app/serviceAccountKey.json
    depends_on:
      - postgres_db
      - mongo_db
    networks:
      - lobbysync_network
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro

volumes:
  postgres_data:
  mongo_data:

networks:
  lobbysync_network:
    driver: bridge
